name: status_checker
description: A Flutter web app to check the status of user-defined URLs.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  supabase_flutter: ^1.10.0
  flutter_dotenv: ^5.1.0 # optional, if you want to load .env at runtime
  url_launcher: ^6.2.5
  # Optional: for better state management if needed later
  provider: ^6.1.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
